package com.alibaba.apiopenplatform.dto.params.chat;

import com.alibaba.apiopenplatform.dto.converter.InputConverter;
import com.alibaba.apiopenplatform.entity.Chat;
import com.alibaba.apiopenplatform.support.chat.attachment.ChatAttachmentConfig;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import java.util.List;

@Data
public class CreateChatParam implements InputConverter<Chat> {

    /**
     * Session ID
     */
    @NotBlank(message = "sessionId cannot be empty")
    private String sessionId;

    /**
     * Conversation ID
     */
    @NotBlank(message = "conversationId cannot be empty")
    private String conversationId;

    /**
     * Question ID, generated by the client
     */
    @NotBlank(message = "questionId cannot be empty")
    private String questionId;

    /**
     * Answer ID, generated by server
     */
    private String answerId;

    /**
     * Product ID, must be the same as the product ID used to create the session
     */
    @NotBlank(message = "productId cannot be empty")
    private String productId;

    /**
     * Question
     */
    @NotBlank(message = "question cannot be empty")
    private String question;

    /**
     * Multi-modal content
     */
    private List<ChatAttachmentConfig> attachments;

    /**
     * MCP servers to use in chat
     */
    private List<String> mcpProducts;

    /**
     * If need stream
     */
    private Boolean stream = true;

    /**
     * If need memory
     */
    private Boolean needMemory = true;
    
    private Boolean enableWebSearch = false;
    
    private String searchType = "";
}
